sbertix/Swiftagram

- README.md
- Sources/Swiftagram/Authentication/Basic/BasicAuthenticator.swift
- Sources/Swiftagram/Authentication/Basic/Checkpoint.swift
- Sources/Swiftagram/Authentication/Basic/TwoFactor.swift
- Sources/Swiftagram/Authentication/Secret/Secret.swift
- Sources/Swiftagram/Authentication/Visual/WebView.swift
- Tests/SwiftagramTests/SwiftagramAuthenticatorTests.swift
> Update to `2.0.1`

- .github/workflows/lint.yaml
- .github/workflows/test.yaml
- Sources/SwiftagramCrypto/Endpoints/EndpointFeed.swift
- Tests/SwiftagramTests/SwiftagramEndpointTests.swift
> Update to `3.1.1`

- Sources/SwiftagramCrypto/Endpoints/EndpointMedia.swift
> Update to `4.0.1`

- Sources/Swiftagram/Models/Comment.swift
> Update to `4.0.2`

- Sources/Swiftagram/Models/Media.swift
> Adding `code` and `hasLiked` to `Media`

- Sources/Swiftagram/Models/Media.swift
- Sources/SwiftagramCrypto/Endpoints/EndpointMedia.swift
- Tests/SwiftagramTests/SwiftagramEndpointTests.swift
- Tests/SwiftagramTests/SwiftagramModelsTests.swift
> Update to `4.0.3`

- Sources/SwiftagramCrypto/Endpoints/EndpointMedia.swift
> Update to `4.1.1`

- Sources/Swiftagram/Extensions/Agnostic.swift
- Sources/SwiftagramCrypto/Endpoints/EndpointMedia.swift
- Sources/SwiftagramCrypto/Endpoints/EndpointMediaComponents.swift
- Sources/SwiftagramCrypto/Extensions/Deprecations.swift
- Tests/SwiftagramTests/Extensions.swift
- Tests/SwiftagramTests/SwiftagramEndpointTests.swift
- docs/README.md
> Update to `4.1.2`

- Package.swift
> Update to `4.1.3`

- .swiftlint.yml
- Sources/Swiftagram/Client/Client.swift
- Sources/SwiftagramCrypto/Authentication/Basic/BasicAuthenticator.swift
> Update to `4.2.1`

- Sources/Swiftagram/Extensions/Deprecations.swift
- Sources/Swiftagram/Models/Specialized/User.swift
- docs/README.md
> Update to `4.2.2`

- Sources/Swiftagram/Models/Specialized/Comment.swift
> Update to `4.2.3`

- Sources/Swiftagram/Client/Client.swift
- Sources/Swiftagram/Extensions/Deprecations.swift
- Sources/SwiftagramCrypto/Endpoints/EndpointMedia.swift
- Sources/SwiftagramCrypto/Endpoints/EndpointMediaComponents.swift
- Tests/SwiftagramTests/AuthenticatorTests.swift
> Update to `4.2.5`

- Sources/Swiftagram/Endpoints/EndpointFriendship.swift
> Update to `4.2.6`

- Sources/Swiftagram/Models/Specialized/Location.swift
- Sources/SwiftagramCrypto/Endpoints/EndpointMedia.swift
- Tests/SwiftagramTests/AuthenticatorTests.swift
- Tests/SwiftagramTests/ModelTests.swift
> Update to `4.2.7`

- Sources/Swiftagram/Endpoints/EndpointMedia.swift
> Update to `4.2.8`

- Sources/Swiftagram/Endpoints/EndpointDirect.swift
- Sources/Swiftagram/Endpoints/EndpointMedia.swift
- Sources/Swiftagram/Extensions/Requestable.swift
- Sources/Swiftagram/Models/Specialized/Conversation.swift
> Update to `4.2.9`

- Examples/Followers/Followers.xcodeproj/project.pbxproj
- Examples/Followers/Followers.xcodeproj/xcshareddata/xcschemes/Followers.xcscheme
- Examples/Followers/Followers/Followers/FollowersModel.swift
- Examples/Followers/Followers/Followers/FollowersView.swift
- Sources/Swiftagram/Endpoints/EndpointMedia.swift
- Tests/SwiftagramTests/EndpointTests.swift
> Update to `4.2.10`

- Sources/Swiftagram/Models/Specialized/Section.swift
> Update to `5.0.1`

- Package.swift
- Sources/Swiftagram/Authentication/Authenticator+Keys.swift
- Sources/Swiftagram/Authentication/Visual/Authenticator+Visual.swift
- docs/README.md
> Update to `5.0.3`

- .github/workflows/chatops.yml
- .github/workflows/merge.yml
- .github/workflows/release.yml
- **actions**: execute `release` on Ubuntu
- **actions**: fix `merge` definition
> chore(actions): execute `release` on Ubuntu

- .github/workflows/chatops.yml
- .github/workflows/merge.yml
- .github/workflows/release.yml
- **actions**: execute `release` on Ubuntu
- **actions**: fix `merge` definition
> chore(actions): fix `merge` and `release` definitions

- .github/workflows/pull_request.yml
- .github/workflows/push.yml
> ci(actions): improve PR-related `push`

- .github/workflows/chatops.yml
- .github/workflows/merge.yml
- .github/workflows/push.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- **actions**: improve on filtering changes
> ci(actions): improve on filtering changes

- .github/workflows/chatops.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- **actions**: fix typo in `release.yml`
> ci(actions): fix typo in `release.yml`

- Sources/Swiftagram/Models/Specialized/User.swift
- docs/README.md
- **models**: add account type to `User` `access`
- **docs**: update docs reference in `README.md`
> feat(models): add account type to `User` `access`

- Package.swift
- Sources/Swiftagram/Authentication/Authenticator.swift
- Sources/Swiftagram/Endpoints/Archived/Endpoint+Archived.swift
- Sources/Swiftagram/Endpoints/Explore/Endpoint+Explore.swift
- Sources/Swiftagram/Endpoints/Media/Endpoint+Media.swift
- Sources/Swiftagram/Endpoints/Posts/Endpoint+Posts.swift
- Sources/Swiftagram/Endpoints/Recent/Endpoint+Recent.swift
- Sources/Swiftagram/Endpoints/User/Endpoint+User.swift
- Sources/Swiftagram/Endpoints/User/Endpoint+Users.swift
- Sources/Swiftagram/Models/Specialized/Conversation.swift
- Sources/Swiftagram/Models/Specialized/SavedCollection.swift
- Sources/Swiftagram/Models/Specialized/Section.swift
- Sources/SwiftagramCrypto/Authentication/Authenticator+Keychain.swift
- docs/CODE_OF_CONDUCT.md
- **deps**: update `ComposableRequest` to `5.1.0`
- **endpoints**: update `ranks to use `UUID`
- **docs**: update `CODE_OF_CONDUCT.md`
> feat(deps): update `ComposableRequest` to `5.1.0`

- .github/dependabot.yml
* [`f0f4643`](http://github.com/sbertix/Swiftagram/commit/f0f46437799727aa8d7c30cc945f289284ebc2c8) - ci(actions): support Dependabot in Actions
> ci(actions): support Dependabot in Actions

- .github/workflows/pull_request.yml
- .github/workflows/push.yml
> ci(actions): support Actions in forks

- .github/workflows/pull_request.yml
> ci(actions): avoid duplication in `pull_request`

- .github/workflows/push.yml
> ci(actions): fix docs generation

- .github/workflows/pull_request.yml
- .github/workflows/push.yml
* [`0091121`](https://github.com/sbertix/Swiftagram/pull/219/commits/576fd3ce3805a08c7865a31d7a8793caf0ded502) ci(actions): avoid duplication in docs
* [`576fd3c`](https://github.com/sbertix/Swiftagram/pull/219/commits/576fd3ce3805a08c7865a31d7a8793caf0ded502) ci(actions): update changelog checkout depth
> ci(actions): avoid duplication in docs

- Examples/Authenticator/Authenticator/LoginView.swift
- Examples/Followers/Followers/LoginView.swift
- Package.swift
- Sources/Swiftagram/Endpoints/Recent/Endpoint+Recent.swift
- Tests/SwiftagramTests/EndpointTests.swift
- docs/README.md
* [`4e11b0d`](http://github.com/sbertix/Swiftagram/commit/4e11b0d241b915eae8058ca561400ee557241d83) - feat(endpoints): support delay between pages
* [`f01680f`](http://github.com/sbertix/Swiftagram/commit/f01680fe7a6488f97bb7bed270be56df28ec3765) - fix(examples): update `LoginViewController` access
> feat(endpoints): support delay between pages

- Package.swift
- Sources/Swiftagram/Endpoints/Endpoint.swift
- Sources/Swiftagram/Endpoints/Recent/Endpoint+Recent.swift
* [`36e37a6`](http://github.com/sbertix/Swiftagram/commit/36e37a6ac855ce366f940c14aae128576cc2aff7) - fix(endpoints): simplify timeline definition
> fix: prepare for Xcode 13

- .gitignore
- Examples/Authenticator/Authenticator.xcodeproj/project.pbxproj
- Examples/Authenticator/Authenticator.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- Examples/Authenticator/Authenticator.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- Examples/Authenticator/Authenticator.xcodeproj/xcshareddata/xcschemes/Authenticator.xcscheme
- Package.swift
- Sources/Swiftagram/Endpoints/Endpoint.swift
- Sources/Swiftagram/Endpoints/Recent/Endpoint+Recent.swift
- Sources/Swiftagram/Endpoints/Saved/Endpoint+SavedCollection.swift
- Sources/Swiftagram/Models/Specialized/SavedCollection.swift
- Sources/Swiftagram/Models/Specialized/Specialized.swift
- Tests/SwiftagramTests/EndpointTests.swift
- Tests/SwiftagramTests/Shared/Media+Content.swift
* [`a4ebf6a`](http://github.com/sbertix/Swiftagram/commit/a4ebf6ad5cc4f3f6333ca786c21e99110851928e) - fix(endpoints): simplify timeline definition
* [`f9ccf03`](http://github.com/sbertix/Swiftagram/commit/f9ccf039687c3062ce292c40fbf9b586432c5f45) - feat: update collection endpoints
* [`b567183`](http://github.com/sbertix/Swiftagram/commit/b5671833acd016605ecce44ca5f607d4f5804cdf) - fix: lint and style code
> feat: update collection endpoints and simplify timeline definition
